version: '3'
services:
  innovationcloud-web:
    image: trzl/innovationcloud-web
    container_name: innovationcloud-web
    restart: unless-stopped
    expose:
      - "80"
      - "443"
    environment:
      VIRTUAL_HOST: innovationcloud.tbrownkcdev.com
      LETSENCRYPT_HOST: innovationcloud.tbrownkcdev.com
      LETSENCRYPT_EMAIL: brownty47@gmail.com
networks:
  default:
    external:
      name: webproxy
